name: tutorial
description: Flutter Data tutorial app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-0 <4.0.0"

dependencies:
  copy_with_extension: ^5.0.4
  flutter:
    sdk: flutter
  flutter_data: ^1.5.14
  hooks_riverpod: ^2.1.1
  isar_flutter_libs: ^4.0.0-dev.14
  json_annotation: ^4.7.0
  path_provider: ^2.0.11

dependency_overrides:
  flutter_data:
    path: ../flutter_data

dev_dependencies:
  build_runner: ^2.4.6
  copy_with_extension_gen: ^5.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1

flutter:
  uses-material-design: true
